"""fix tables

Revision ID: 098fec246d84
Revises: 80bcba1462de
Create Date: 2024-12-23 16:58:38.171305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098fec246d84'
down_revision: Union[str, None] = '80bcba1462de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acknowledgements', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acknowledgements', 'acknowledged_at')
    # ### end Alembic commands ###
