"""make sales columns auto 0

Revision ID: 16bb007f34e0
Revises: 336942a48ab9
Create Date: 2024-12-04 16:47:06.646178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bb007f34e0'
down_revision: Union[str, None] = '336942a48ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cells', 'purchase_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cells', 'purchase_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
