"""Add purchase price to cell

Revision ID: 336942a48ab9
Revises: df6d50905212
Create Date: 2024-12-04 16:03:43.714162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '336942a48ab9'
down_revision: Union[str, None] = 'df6d50905212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('purchase_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cells', 'purchase_price')
    # ### end Alembic commands ###
