"""Initial commit

Revision ID: 77282393a6a4
Revises: 
Create Date: 2024-12-04 14:26:36.594676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77282393a6a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acc_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('car_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('image', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('dmc', sa.String(), nullable=True),
    sa.Column('assessment_doc', sa.String(), nullable=True),
    sa.Column('tax_doc', sa.String(), nullable=True),
    sa.Column('selling_price', sa.Numeric(), nullable=True),
    sa.Column('transport_fees', sa.Numeric(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(), nullable=True),
    sa.Column('discount', sa.Numeric(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('sold_date', sa.DateTime(), nullable=True),
    sa.Column('tax', sa.Numeric(), nullable=True),
    sa.Column('other_expenses', sa.Numeric(), nullable=True),
    sa.Column('proof_of_payment', sa.String(), nullable=True),
    sa.Column('ebm_receipt', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('proof', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('where_to', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('contra_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contra_id'], ['cash_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debt_management',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('selling_price', sa.Numeric(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(), nullable=True),
    sa.Column('other_expenses', sa.Numeric(), nullable=True),
    sa.Column('tax', sa.Numeric(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('sold_date', sa.DateTime(), nullable=True),
    sa.Column('discount', sa.Numeric(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trim', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('acc_subcategories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['acc_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car_products.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['cash_book.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts_subcategories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['parts_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trims_cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('trim_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trim_id'], ['trims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accessories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_num', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('other_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('replaces', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('brands', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('positions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subcategory_id'], ['acc_subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_num', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('other_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('replaces', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('brands', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('positions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subcategory_id'], ['parts_subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trims_engines_and_cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=True),
    sa.Column('trim_car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trim_car_id'], ['trims_cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acc_sub_cat_fitment',
    sa.Column('fitment_id', sa.Integer(), nullable=True),
    sa.Column('sub_cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fitment_id'], ['trims_engines_and_cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_cat_id'], ['acc_subcategories.id'], ondelete='CASCADE')
    )
    op.create_table('accessory_fitment',
    sa.Column('fitment_id', sa.Integer(), nullable=True),
    sa.Column('accessory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accessory_id'], ['accessories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fitment_id'], ['trims_engines_and_cars.id'], ondelete='CASCADE')
    )
    op.create_table('car_fitments',
    sa.Column('fitment_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fitment_id'], ['trims_engines_and_cars.id'], ondelete='CASCADE')
    )
    op.create_table('part_fitment',
    sa.Column('fitment_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fitment_id'], ['trims_engines_and_cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE')
    )
    op.create_table('part_sub_cat_fitment',
    sa.Column('fitment_id', sa.Integer(), nullable=True),
    sa.Column('sub_cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fitment_id'], ['trims_engines_and_cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_cat_id'], ['parts_subcategories.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part_sub_cat_fitment')
    op.drop_table('part_fitment')
    op.drop_table('car_fitments')
    op.drop_table('accessory_fitment')
    op.drop_table('acc_sub_cat_fitment')
    op.drop_table('trims_engines_and_cars')
    op.drop_table('parts')
    op.drop_table('accessories')
    op.drop_table('trims_cars')
    op.drop_table('parts_subcategories')
    op.drop_table('inquiries')
    op.drop_table('actions')
    op.drop_table('acc_subcategories')
    op.drop_table('users')
    op.drop_table('trims')
    op.drop_table('products')
    op.drop_table('parts_categories')
    op.drop_table('files')
    op.drop_table('engines')
    op.drop_table('debt_management')
    op.drop_table('cash_book')
    op.drop_table('cars')
    op.drop_table('car_products')
    op.drop_table('acc_categories')
    # ### end Alembic commands ###
