"""Add battery feature

Revision ID: df6d50905212
Revises: 77282393a6a4
Create Date: 2024-12-04 14:32:48.590432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6d50905212'
down_revision: Union[str, None] = '77282393a6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batteries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cells_count', sa.Integer(), nullable=False),
    sa.Column('sold_fully', sa.Boolean(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(), nullable=False),
    sa.Column('selling_price', sa.Numeric(), nullable=False),
    sa.Column('other_expenses', sa.Numeric(), nullable=True),
    sa.Column('tax', sa.Numeric(), nullable=True),
    sa.Column('discount', sa.Numeric(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('sold_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('cell_no', sa.String(), nullable=False),
    sa.Column('selling_price', sa.Numeric(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('other_expenses', sa.Numeric(), nullable=True),
    sa.Column('tax', sa.Numeric(), nullable=True),
    sa.Column('sold_date', sa.DateTime(), nullable=True),
    sa.Column('discount', sa.Numeric(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['battery_id'], ['batteries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('actions', sa.Column('battery_id', sa.Integer(), nullable=True))
    op.add_column('actions', sa.Column('cell_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'actions', 'cells', ['cell_id'], ['id'])
    op.create_foreign_key(None, 'actions', 'batteries', ['battery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_column('actions', 'cell_id')
    op.drop_column('actions', 'battery_id')
    op.drop_table('cells')
    op.drop_table('batteries')
    # ### end Alembic commands ###
